neillturner/kitchen-puppet

kitchen-puppet.gemspec, lib/kitchen/provisioner/puppet_apply.rb, provisioner_options.md
Allows user to install any specified custom facts to the test-node. This is useful if facter is ever ran after or during the initial 'puppet apply' to the node.
Currently, any custom facter facts that are specified are added as environment variables to the puppet_apply command. This ensures that any resources running the "facter" binary, or depending on facter running after that provisioning command will incorporate the new facter facts
=> Add install_custom_facts provisioner option

lib/kitchen/provisioner/puppet_apply.rb
When parsing custom_facts to a file, we need to parse a hash of strings,
not symbols as facter reads a yaml file of strings.
Previously the file left by install_custom_facts was unusable with facter
@neillturner, passes lint test. I'll wait for your :+1: before shipping and releasing a new version
=> Use custom_facts as hash of strings not keys

lib/kitchen/provisioner/puppet_apply.rb, provisioner_options.md
TK logs are difficult to sort through if only looking for provisioner
logs, aka puppet logs of the puppet run. Allows a local logfile to be
written to as well as the console (if wanted)
=> Add logdest provisioner option

lib/kitchen/provisioner/puppet_apply.rb
Looks like the hiera_eyaml option was not honored when the puppet_platform was specified.
This PR fixes this.
=> honor the hiera_eyaml option when puppet_platform is set

lib/kitchen/provisioner/puppet_apply.rb, provisioner_options.md
the deep_merge gem must be installed in order to support the deep_merge mode of hiera (see https://docs.puppetlabs.com/hiera/1/lookup_types.html)
* added support a new option hiera_deep_merge
* enhanced the doc in provisioner_options.md
=> provide support for hiera deep merge mode

lib/kitchen/provisioner/puppet_agent.rb, lib/kitchen/provisioner/puppet_apply.rb
On some systems, most notably docker containers, wget might not be
installed. This will cause the wget command to fail. apt-get install
will then install puppet from the official debian repos. This was a
silent failure, has the user had to watch the output to notice something
was amiss.
=> Make sure wget is installed before downloading

lib/kitchen/provisioner/puppet_apply.rb, provisioner_options.md
Our use case: apart from puppet code itself we need to deliver supporting testing facilities which is part of our puppet manifest git repo.
In future it can be extended to also use fully git based code within test vm for converge (instead of /tmp/kitchen)
=> Add ability to initialize /etc/puppet from git repository

provisioner_options.md
As given, the example does not work, and requires the overriding settings to be inside a `provisioner` block.
A working example can be seen here: https://github.com/neillturner/kitchen-ansible#testing-multiple-playbooks
=> Correct example in provisioner_options.md

lib/kitchen/provisioner/puppet_agent.rb, lib/kitchen/provisioner/puppet_apply.rb, provisioner_options.md
I know that puppet 2.7 is deprecated, however one sometimes finds themselves working in legacy environments that are still using 2.7.
In order to move to puppet 3+ we need to write tests for puppet 2.7 to ensure that we don't break the legacy systems before they are able to upgrade, ensuring we support both 2.7 and 3+.
This PR adds support for puppet 2.7. Due to the dependencies on debian for the puppetlabs packages we need to be able to specify facter and hiera package versions to install.
=> Puppet 2.7 support

lib/kitchen/provisioner/puppet_apply.rb
This error was masked because /etc/puppet usually exists from installing an official puppet package.
=> fix creating directory that requires root

provisioner_options.md
The other patch missed the apply section.
=> Fix suite override example for puppet apply

lib/kitchen/provisioner/puppet_apply.rb
I'm using the vagrant driver for testkitchen, which allows me to share folders with the VM. I have a puppet repository with modules stored in a few different folders, so the existing copy mechanisms don't work. I think this is kind of rough, let me know if I should change my approach or add anything.
=> Synced modules

lib/kitchen/provisioner/puppet_apply.rb
Hi,
I've patched copy_self_as_module to not include 'spec' and 'pkg' module subdirectories of the module being developed. The main reason for this change is smother interoperability with puppetlabs_spec_helper which creates symlinks in spec/fixtures/modules that than break test kitchen.
Please include my change in next kitchen-puppet release.
Petr.
=> Don't include spec and pkg subdirectories to the module

lib/kitchen/provisioner/puppet_apply.rb, provisioner_options.md, spec/kitchen/provisioner/puppet_apply_spec.rb
This allows kitchen-puppet to determine the correct apt repo to use when
installing Puppet, instead of requiring manual user settings.
Doing this, however, deprecates the configuration of `puppet-platform`,
as this is now set from the platform configuration in
`.kitchen.yml`.
I have left the default `puppet_apt_repo` configuration parameter set to
ubuntu precise. I can be convinced fairly easily to change this to
trusty, yet I don't really see the benefit after the merge of this
patch, as `kitchen-puppet` will now install the correct apt repo based
on the test-suite's platform without further configuration.
Due to this deprecation we will likely need to increase the minor version from
`0` to `1` according to semver rules. cc: @neillturner
As discovered in Issue #67, the puppet repo for …
=> Fix Apt Repo Settings

Gemfile
Lock Gem versions, forcing explicit upgrade of gem versions.
Prevents issues found on previous PR's where a new version of a gem is
released before the PR is merged into master.
=> Lock Gem versions

lib/kitchen/provisioner/puppet_apply.rb, provisioner_options.md
Instead of changing the method arguments passed to a function, actually
call the function properly. This keeps the code functioning in exactly
the same fashion as it was previously, yet updates style to conform to
rubocop's update of the SymbolProc cop.
--------
Setting the `platform` configuration option _will_ break
things. Provisioner options are generally set at the global level, and
if a developer has multiple suites of differing platforms, this will
cause things to break. By inheriting the `Configurable` module from
test-kitchen we are able to read the platform name for each test suite's
platform correctly. This will even read the platform correctly if
`.kitchen.yml` only has one test suite but multiple platforms defined.
I can't think of a solid case where the `platform` …
=> Fix rubocop issues

.gitignore, .rubocop.yml, spec/spec_helper.rb
This is handy when using `bundle install --standalone`
* .gitignore
* rubocop
* coverage
=> Ignore /bundle directory

lib/kitchen/provisioner/puppet_apply.rb, provisioner_options.md, spec/kitchen/provisioner/puppet_apply_spec.rb
Adds Hiera Package Name configuration for installing hiera from a different package name than `hiera-puppet`
=> Add Hiera Package Name Configuration

README.md
* It could take some time to setup kitchen-puppet if you don't use
* 'puppet module generate' to create the module and try to find out why
* your module couldn't be found when puppet-apply is executed.
=> Add a doc hint that metadata.json is needed.

lib/kitchen/provisioner/puppet_apply.rb, spec/kitchen/provisioner/puppet_apply_spec.rb
if require_puppet_collections is specified don't specify the manifest_dir. My understanding is you can only install puppet v4 via collections so this should work. please review and merge if you agree with this change. @grubernaut  @ytsarev
=> ManifestDir is Deprecated in Puppet4

lib/kitchen/provisioner/puppet_apply.rb, provisioner_options.md, spec/kitchen/provisioner/puppet_apply_spec.rb
this allows custom options to be added to the puppet pply command. for example --no-stringify_facts.
please review. @ytsarev @grubernaut . i need to do a little testing before i merge
=> Custom options

lib/kitchen/provisioner/puppet_apply.rb
When behind a corporate proxy and using http proxy parameters, wget is failing because https_proxy was not being set properly
=> Fix typo with wget https proxy attribute

lib/kitchen/provisioner/puppet_apply.rb
The hiera.yaml file needs to be in /opt/puppetlabs/code when using puppet_collections. If not, it won't be picked up by puppet apply automatically.
=> correct path for heira.yaml when using puppet_collections

lib/kitchen/provisioner/puppet_apply.rb, provisioner_options.md, spec/kitchen/provisioner/puppet_apply_spec.rb
* New puppet_whitelist_exit_code configuration option
* Move remove_repo to cleanup section so it does not hide puppet exit
code
* Relevant documentation
=> Provide ability to whitelist puppet exit code.

lib/kitchen/provisioner/puppet_agent.rb, lib/kitchen/provisioner/puppet_apply.rb
fixes #114 by adding an additional conditional check when setting the redhat package version number.
=> add puppet v3 support on amazon linux

.travis.yml, Gemfile, kitchen-puppet.gemspec
Update net-ssh gem to properly working gem version.
v2.9.4 currently throws the following warning:
```
net-ssh-2.9.4/lib/net/ssh/transport/session.rb:67:in `initialize':
Object#timeout is deprecated, use Timeout.timeout instead.
```
=> Update net-ssh gem

lib/kitchen/provisioner/puppet_apply.rb
When kitchen tries to install puppet, it fails if there are proxy settings on the host.
=> fix: add a CR to avoid trouble with proxy settings concatenation

lib/kitchen/provisioner/puppet_apply.rb, spec/kitchen/provisioner/puppet_apply_spec.rb
When running with the kitchen-docker driver. I ran into a case where I don't need to run puppet with sudo.
=> allow puppet_cmd to be without sudo

.rubocop.yml, lib/kitchen/provisioner/puppet/librarian.rb, lib/kitchen/provisioner/puppet_apply.rb, spec/kitchen/provisioner/puppet_apply_spec.rb
Where I work we have a convention of installing all bundled gems at vendor/bundle. This can make the process of copying the module under test into the sandbox a really long one.
Used like:
```yaml
---
provisioner:
name: puppet_apply
excluded_paths_from_module:
- '/vendor'
```
=> configure what is excluded when copying module

lib/kitchen/provisioner/puppet_apply.rb
Looks like a typo, it should export https_proxy instead of http_proxy.
=> Fix exporting https_proxy env var during Omnibus installs

lib/kitchen/provisioner/puppet/librarian.rb
This fixes #85 
We were experiencing the same issue as the OP, and it turns out it was because the `puppetfile_path` config wasn't referencing an absolute path. Once this was changed, relocating the `Puppetfile` to `spec/fixtures` (or any other path) works as expected. 
This change will work fine with existing implementations, as `File.expand_path` will be a noop on the default `puppetfile_path`, as that is already an absolute path.
=> Use expand_path to set absolute path for puppetfile_path

lib/kitchen/provisioner/puppet_apply.rb, spec/kitchen/provisioner/puppet_apply_spec.rb
This PR add supports for installing Puppet 4+ on Windows. (Using the `puppet-agent` installers available at https://downloads.puppetlabs.com/windows) 
* It is using the existing `require_puppet_collections` parameter.
* If set to `true`, the `puppet-agent` installers are used (Puppet 4)
* If set to `false`, the `puppet` installers are used (Puppet 3)
I also fixed the Puppet 3 install logic to allow `puppet_version` to be set to `latest`. (and made this the default)
=> Support installing Puppet 4+ on windows

lib/kitchen/provisioner/puppet_apply.rb
I believe this code is redundant...
On windows, hiera data files end up being copied  to `C:/var/lib/` instead of `C:/var/lib/hiera` when `hiera_data_remote_path` is set to `/var/lib/hiera`. (I suspect because `C:/var/lib/hiera` does not exist by default)
With this change, the `C:/var/lib/hiera` folder is created before the copy and files do end up being copied to `C:/var/lib/hiera`.
Not sure why there is special logic that skip creating `/var/lib/hiera` in the first place?
=> Fix copy of hiera data files

lib/kitchen/provisioner/puppet_apply.rb, provisioner_options.md
Hi there, this allows the option to run puppet with `--parser=future` enabled. This is useful if you're testing with puppet 3 modules which use the future parser features ( see https://docs.puppet.com/puppet/3.8/experiments_future.html )
=> Add future parser option to puppet apply

lib/kitchen/provisioner/puppet_apply.rb, spec/kitchen/provisioner/puppet_apply_spec.rb
On Windows hosts the default value of hiera `datadir` is "%CommonAppData%\PuppetLabs\hiera\var"
=> Fix default value of "hiera_data_remote_path" for Windows

lib/kitchen/provisioner/puppet_apply.rb, spec/kitchen/provisioner/puppet_apply_spec.rb
Following up on #166 this change sets the default value of hiera's `datadir` based on the version of puppet installed.
* For puppet v3 (no change):
* windows: `C:/ProgramData/PuppetLabs/hiera/var`
* linux: `/var/lib/hiera`
* For puppet v4 and later:
* windows: `C:/ProgramData/PuppetLabs/code/environments/production/hieradata`
* linux: `/etc/puppetlabs/code/environments/production/hieradata`
=> Fix default values for hiera_data_remote_path based on puppet_version

lib/kitchen/provisioner/puppet_apply.rb
Use `Invoke-WebRequest` instead of its `wget` alias. (Windows Server 2008 SP2  doesn't have a `wget` alias for `Invoke-WebRequest`)
This will keep kitchen-puppet working for the poor souls who are still using `Windows Server 2008 SP2` 👴
=> Fix installation of puppet on Windows Server 2008 SP2

README.md
Remove non-existing provisioner.
Fix indentation in hiera_writer_files section (it was producing empty `datacenter/vagrant.yaml` but was creating files `logstash_servers` and `hosts`)
Fixes #175.
=> Update README.md with hieradata example

lib/kitchen/provisioner/puppet_apply.rb, provisioner_options.md, spec/kitchen/provisioner/puppet_apply_spec.rb
Puppet 3 has been end of life for a while now [1] so lets make the collections install method (and puppet 4/5) the default.
[1] https://rnelson0.com/2016/10/25/puppet-3-end-of-life-12312016/
=> Puppet 3 is EOL

lib/kitchen/provisioner/puppet_apply.rb
https://github.com/neillturner/kitchen-puppet/issues/182
Mapping to to_s is redundant (and doesn't allow you to see if v is a hash).
=> Allow custom facts to have hash

lib/kitchen/provisioner/puppet_apply.rb
Previously only worked with Hash, now supports arrays. 
ex:
```
list_of_ips:
- 10.0.0.1
- 192.168.10.10
```
Previous Output:
```
Facter.add(:ossec_manager_ips) do
setcode do
"["10.0.0.1", "192.168.10.10"]"
end
end
```
New Output:
```
Facter.add(:ossec_manager_ips) do
setcode do
["10.0.0.1", "192.168.10.10"]
end
end
```
Current issues:
- Cannot create an empty list. (Is there a better way to be adding facts other than passing them into kitchen.yml?)
=> Add array support to custom facts

lib/kitchen/provisioner/puppet_agent.rb, spec/kitchen/provisioner/puppet_agent_spec.rb
* previously we could not tell kitchen that an exit code of 2
was a success.  This fixes that by take the code from puppet apply
and adding it to the puppet agent.
=> Adds whitelist_exit codes to puppet_agent

lib/kitchen/provisioner/puppet_agent.rb, lib/kitchen/provisioner/puppet_apply.rb, provisioner_options.md, spec/kitchen/provisioner/puppet_agent_spec.rb, spec/kitchen/provisioner/puppet_apply_spec.rb
getchef.com is 301'd to chef.io which is the future looking domain.
Signed-off-by: JJ Asghar <jj@chef.io>
=> Updated URL for chef

Gemfile, lib/kitchen/provisioner/puppet/librarian.rb
Previously kitchen-puppet didn't configure Librarian-puppet with the logger from Kitchen, so all logging messages were lost when trying to resolve dependencies.
This adds a "UI" for the Librarian environment that forwards all log messages to the Kitchen logger.
=> Add Kitchen logger to Librarian

lib/kitchen/provisioner/puppet_apply.rb
It looks like Puppetlabs have changed up how the Windows installers are stored in their downloads directory.
I've tweaked the installer logic for puppet-agent to work with the new way that the MSI's are stored which should hopefully add a bit of future-proofing too.
I've also added support for pre/post install commands in Windows so that absolute worst case people can use their own logic.
=> Tweak puppet-agent Windows Installers
