- lib/kitchen/provisioner/puppet_apply.rb
Previous commit did not stick to sandbox rules of TK.
Fixes previous commit
> Fix from previous commit

- kitchen-puppet.gemspec
- lib/kitchen/provisioner/puppet_agent.rb
- lib/kitchen/provisioner/puppet_apply.rb
Fix all styling issues to make CI build green
> Fix rubocop issues

- lib/kitchen/provisioner/puppet_apply.rb
- spec/kitchen/provisioner/puppet_apply_spec.rb
It provides functionality of dynamic fact generation
as desribed in https://docs.puppetlabs.com/facter/2.2/custom_facts.html
> Ability to export FACTERLIB

- README.md
- spec/kitchen/provisioner/puppet/librarian_spec.rb
- spec/kitchen/provisioner/puppet_apply_spec.rb
Adds config change tests, to ensure configuration changes are set
> Add config change tests

- lib/kitchen/provisioner/puppet_apply.rb
Reverts neillturner/kitchen-puppet#58
> Revert "Synced modules"

- lib/kitchen/provisioner/puppet_apply.rb
- spec/kitchen/provisioner/puppet_apply_spec.rb
I use this functionality to upload serverspec test suite for further `verify`
> Ability to upload spec files for further testing within an instance

- lib/kitchen/provisioner/puppet_apply.rb
it's safer and on par with the rest of the uploaded things
> Remove spec dir from sandbox in init stage

- .travis.yml
- Gemfile
- README.md
- Rakefile
- TESTING.md
- spec/integration/.gitignore
- spec/integration/.kitchen.yml
- spec/integration/manifests/site.pp
- spec/integration/modules/test/manifests/init.pp
- spec/integration/test/integration/default/serverspec/localhost/test_spec.rb
- spec/integration/test/integration/default/serverspec/spec_helper.rb
Resolves #86 as initial setup of e2e testing facility
> Docker + Travis PoC

- lib/kitchen/provisioner/puppet_apply.rb
- spec/integration/.kitchen.yml
Should fix #94
Also added related integration test
> Do not fail on apt repo detection when platform is unknown

- .rubocop.yml
- .travis.yml
- Gemfile
- kitchen-puppet.gemspec
- lib/kitchen-puppet/version.rb
- lib/kitchen/provisioner/puppet/librarian.rb
- lib/kitchen/provisioner/puppet_agent.rb
- lib/kitchen/provisioner/puppet_apply.rb
proxy support for chef install for busser and ci cleanup
> proxy-support

- lib/kitchen/provisioner/puppet_apply.rb
https://github.com/neillturner/kitchen-puppet/issues/106
* enable the use of puppet_version when using:
`require_puppet_collections: true`
* simplify logic for `install_command_collections` depending on platform
* Apt and Yum installations are now equivalent. Apt left out the actual
installation and left it purely to `custom_install_command`.
* When using puppet collections, the package name for puppet is actually
`puppet-agent` instead of `puppet`.
> support puppet_version when using collections

- .travis.yml
- lib/kitchen-puppet/version.rb
- lib/kitchen/provisioner/puppet_apply.rb
- provisioner_options.md
> Pre install command

- README.md
- lib/kitchen/provisioner/puppet_apply.rb
- spec/kitchen/provisioner/puppet_apply_spec.rb
this is a cleanup version of pull request Add some windows support to Puppet Apply #130 that pass the travis tests
> Windows support

- lib/kitchen-puppet/version.rb
- lib/kitchen/provisioner/puppet_apply.rb
- provisioner_options.md
- spec/kitchen/provisioner/puppet_apply_spec.rb
this is PR Introduce custom_post_install command #131 but i changed the parameter name to custom_post_apply_command so it was very clear that it was called post puppet apply as opposed to post puppet install time
> custom_post_apply

- lib/kitchen-puppet/version.rb
- lib/kitchen/provisioner/puppet_apply.rb
- provisioner_options.md
- spec/kitchen/provisioner/puppet_apply_spec.rb
custom_pre_apply_command correct earlier naming of custom_post_apply_command
> pre_apply_command

- lib/kitchen/provisioner/puppet_apply.rb
- spec/integration/.kitchen.yml
Having issue when using puppet_environment, the value was trying to be appended to a list but was a string.
Have added to the integration test to make sure is tested
> Fix issue with trying to append string to an array

- Gemfile
- lib/kitchen/provisioner/puppet_agent.rb
- lib/kitchen/provisioner/puppet_apply.rb.new
- provisioner_options.md
- spec/kitchen/provisioner/puppet_apply_spec.rb
This is needed to capture detailed existcodes 0 (already converged) and 2 (no failure during apply)
> Add support for multiple whitelisted exit codes on Linux

- lib/kitchen/provisioner/puppet_apply.rb
- provisioner_options.md
> Add show_diff functionality

- lib/kitchen/provisioner/puppet_apply.rb
Hi! 
Currently there is an issue if multiple directories defined in `module_path` (separated by `:`) and there are modules with the same name in these dirs. That is a valid behavior - it happens when people migrate their Puppet workflow from "monolith-repo" to "puppetfile-driven" one.
In current implementation all modules from the left to the right are copying to the sandbox dir (and then to the kitchen instance). So in case of duplicated modules they will be "shuffled" - the content of the _latest_ one will we written on top of the earlier, which is wrong.
This PR fixes that issue: now the precedence of duplicated modules is determined in according to the Puppet Agent's approach: "earliest-module-wins", which is described here: https://docs.puppet.com/puppet/4.9/dirs_modulepath.html#dupli …
> Fix the load order of duplicated modules in "modules_path"

- lib/kitchen/provisioner/puppet_agent.rb
- lib/kitchen/provisioner/puppet_apply.rb
- provisioner_options.md
- spec/kitchen/provisioner/puppet_apply_spec.rb
- puppet agent provisioner (Also adding https_proxy support)
- puppet apply provisioner
- Updates to documentation
- Added spec tests
> Adding support for no_proxy.

- lib/kitchen/provisioner/puppet_apply.rb
- provisioner_options.md
This fixes https://github.com/neillturner/kitchen-puppet/issues/170 by adding support for directory environments.
> Added Support for Puppet4 Environments with environment hiera config

- lib/kitchen/provisioner/puppet_apply.rb
- provisioner_options.md
- spec/kitchen/provisioner/puppet_apply_spec.rb
now that puppet 5 has releases to the general public we should make it the default collection
> make puppet 5 the default collection

- Rakefile
- lib/kitchen-puppet/version.rb
> Adds rake tasks to make releasing this gem easier

- CHANGELOG.md
- lib/kitchen-puppet/version.rb
Please create a a new release for 3.2.0
> prep for release 3.2.0

- lib/kitchen/provisioner/puppet/r10k.rb
- lib/kitchen/provisioner/puppet_apply.rb
- provisioner_options.md
- spec/kitchen/provisioner/puppet_agent_spec.rb
> R10K Support

- lib/kitchen/provisioner/puppet_apply.rb
Ubuntu 18.04
bash --version
GNU bash, version 4.4.20(1)-release (x86_64-pc-linux-gnu)
> Fixes error "bash: line 114: [: too many arguments"
